module.exports = data = [
  {
    name: "Olpers Full Cream Milk Carton (1x8)",
    image: "olpers-full-cream-carton.webp",
    quantity: "1500 ml",
    mango: "hells",
    discountPercentage: "7",
    price: "2800",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: true,
  },
  {
    name: "Nurpur Full Cream Milk Carton (1x8)",
    image: "nurpur-full-cream-carton.webp",
    quantity: "1500 ml",
    discountPercentage: "6",
    price: "2810",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: true,
  },
  {
    name: "Tapal Danedar Tea",
    image: "tapal-dendar-tea.webp",
    quantity: "900 gm",
    discountPercentage: "8",
    price: "1725",
    category: "Beverages",
    subcategory: "Tea",
    featured: false,
    topSeller: true,
  },
  {
    name: "Olpers Full Cream Milk Carton (1x12)",
    image: "olpers-full-cream-carton-12.webp",
    quantity: "1 ltr",
    discountPercentage: "6",
    price: "3060",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: true,
  },
  {
    name: "7up 1.5Ltr Pet (1x6)",
    image: "7up-1.5ltr-pet.webp",
    quantity: "1 unit",
    discountPercentage: "17",
    price: "960",
    category: "Beverages",
    subcategory: "Cold Drinks",
    featured: false,
    topSeller: true,
  },
  {
    name: "Olpers Full Cream Milk Pouch Carton (1x28)",
    image: "olpers-full-cream-pouch-carton.webp",
    quantity: "250 ml",
    discountPercentage: "6",
    price: "1880",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: true,
  },
  {
    name: "Rooh Afza Hamdard",
    image: "roh-afzah.webp",
    quantity: "3 ltr",
    discountPercentage: "10",
    price: "1100",
    category: "Beverages",
    subcategory: "Sharbat",
    featured: false,
    topSeller: true,
  },
  {
    name: "Veet Cream Silk & Fresh Normal",
    image: "veet-cream.webp",
    quantity: "100 gm",
    discountPercentage: "25",
    price: "640",
    category: "Personal Care",
    subcategory: "Skin Care",
    featured: true,
    topSeller: true,
  },
  {
    name: "Chicken Breast Boneless (Fillet) (چکن بون لیس)",
    image: "chicken-breast.webp",
    quantity: "1 kg",
    discountPercentage: "8",
    price: "1085",
    category: "Meat",
    subcategory: "Chicken",
    featured: false,
    topSeller: true,
  },
  {
    name: "Coca Cola 1.5Ltr Pet (1x6)",
    image: "coca-cola-pet.webp",
    quantity: " 1 unit",
    discountPercentage: "12",
    price: "960",
    category: "Beverages",
    subcategory: "Cold Drinks",
    featured: false,
    topSeller: true,
  },
  {
    name: "Rooh Afza Hamdard",
    image: "rooh-afzah.webp",
    quantity: "800 ml",
    discountPercentage: "9",
    price: "340",
    category: "Beverages",
    subcategory: "Sharbat",
    featured: true,
    topSeller: false,
  },
  {
    name: "Shezan Samarqand Sharbat",
    image: "samarqand-sharbat.webp",
    quantity: "800 ml",
    discountPercentage: "9",
    price: "340",
    category: "Beverages",
    subcategory: "Sharbat",
    featured: true,
    topSeller: false,
  },
  {
    name: "Shezan Mango Squash",
    image: "shezan-mango-squash.webp",
    quantity: "1500 ml",
    discountPercentage: "5",
    price: "480",
    category: "Beverages",
    subcategory: "Sharbat",
    featured: true,
    topSeller: false,
  },
  {
    name: "Gaala Desi Ghee (100% Pure)",
    image: "gaala-desi-ghee.webp",
    quantity: "500 gm",
    discountPercentage: "",
    price: "867",
    category: "Grocery",
    subcategory: "Oil and Ghee",
    featured: true,
    topSeller: false,
  },
  {
    name: "Gaala Feta cheese (100% Natural Dairy Product)",
    image: "gaala-feta-cheesa.webp",
    quantity: "200 gm",
    discountPercentage: "",
    price: "450",
    category: "Bakery and Dairy",
    subcategory: "Cheese",
    featured: true,
    topSeller: false,
  },
  {
    name: "MG Naturals – Dried Apples",
    image: "mg-naturals-dried-apples.webp",
    quantity: "200 gm",
    discountPercentage: "15",
    price: "500",
    category: "Dry Fruits and Nuts",
    subcategory: "Dry Fruits",
    featured: true,
    topSeller: false,
  },
  {
    name: "President Mozzarella Cheese Slices",
    image: "president-cheese-slice.webp",
    quantity: " 200 gm",
    discountPercentage: "5",
    price: "750",
    category: "Bakery and Dairy",
    subcategory: "Cheese",
    featured: true,
    topSeller: false,
  },
  {
    name: "Canolive Cooking Oil 1 Litre Pouch",
    image: "canolive-cooking-oil.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "730",
    category: "Grocery",
    subcategory: "Oil and Ghee",
    featured: true,
    topSeller: false,
  },
  {
    name: "Nutella Ferrero Chocolate Jar Hazelnut Spread With Cocoa",
    image: "nutella.webp",
    quantity: "350 gm",
    discountPercentage: "",
    price: "1345",
    category: "Grocery",
    subcategory: "Jam, Honey and Spread",
    featured: true,
    topSeller: false,
  },
  {
    name: "Peeled Onion - چھلا ہوا پیاز",
    image: "onion.webp",
    quantity: "500 gm",
    discountPercentage: "",
    price: "49",
    category: "Fruits and Vegetables",
    subcategory: "Vegetables",
    featured: false,
    topSeller: false,
  },
  {
    name: "Potato - (new)",
    image: "potato.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "69",
    category: "Fruits and Vegetables",
    subcategory: "Vegetables",
    featured: false,
    topSeller: false,
  },
  {
    name: "Tomato (ٹماٹر)",
    image: "tomato.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "86",
    category: "Fruits and Vegetables",
    subcategory: "Vegetables",
    featured: false,
    topSeller: false,
  },
  {
    name: "Ginger - ادرک",
    image: "ginger.webp",
    quantity: "250 gm",
    discountPercentage: "",
    price: "195",
    category: "Fruits and Vegetables",
    subcategory: "Vegetables",
    featured: false,
    topSeller: false,
  },
  {
    name: "Garlic لہسن",
    image: "garlic.webp",
    quantity: "250 gm",
    discountPercentage: "",
    price: "104",
    category: "Fruits and Vegetables",
    subcategory: "Vegetables",
    featured: false,
    topSeller: false,
  },
  {
    name: "Apple kala kullu (سیب کالا کلو)",
    image: "apple.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "429",
    category: "Fruits and Vegetables",
    subcategory: "Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Banana - کیلا",
    image: "banana.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "339",
    category: "Fruits and Vegetables",
    subcategory: "Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Grapes Sunderkhani 500gm انگور سنررخانی",
    image: "grapes.webp",
    quantity: "500 gm",
    discountPercentage: "",
    price: "438",
    category: "Fruits and Vegetables",
    subcategory: "Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Guava-امرود",
    image: "guava.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "294",
    category: "Fruits and Vegetables",
    subcategory: "Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Kiwi (کیوی) (Approx. 480 G to 510 G)",
    image: "kiwi.webp",
    quantity: "500 gm",
    discountPercentage: "",
    price: "271",
    category: "Fruits and Vegetables",
    subcategory: "Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Melon - خربوزہ",
    image: "melon.webp",
    quantity: "1500 gm",
    discountPercentage: "",
    price: "229",
    category: "Fruits and Vegetables",
    subcategory: "Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Olpers Full Cream Milk",
    image: "olpers-full-cream-milk.webp",
    quantity: "1 ltr",
    discountPercentage: "5",
    price: "239",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Olpers Procal+ Low Fat Milk",
    image: "olphers-procal.webp",
    quantity: "1 ltr",
    discountPercentage: "5",
    price: "259",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Nurpur Full Cream Milk",
    image: "nurpur-cream-milk.webp",
    quantity: "1 ltr",
    discountPercentage: "6",
    price: "250",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Dairy Pure Milk",
    image: "dairy-pure-milk.webp",
    quantity: "1 ltr",
    discountPercentage: "6",
    price: "200",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Abbotts Ensure Strawberry 400gm",
    image: "ensure-strawberry.webp",
    quantity: "400 gm",
    discountPercentage: "4",
    price: "1810",
    category: "Bakery and Dairy",
    subcategory: "Cream and Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Dawn Bran Bread 340g",
    image: "dawn-bread.webp",
    quantity: "340 gm",
    discountPercentage: "",
    price: "130",
    category: "Bakery and Dairy",
    subcategory: "Breads",
    featured: false,
    topSeller: false,
  },
  {
    name: "Dawn Bread Crumbs 1kg",
    image: "dawn-bread-crumbs.webp",
    quantity: "1000gm",
    discountPercentage: "",
    price: "270",
    category: "Bakery and Dairy",
    subcategory: "Breads",
    featured: false,
    topSeller: false,
  },
  {
    name: "Dawn Bread Plain Large 725g",
    image: "dawn-bread-large.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "200",
    category: "Bakery and Dairy",
    subcategory: "Breads",
    featured: false,
    topSeller: false,
  },
  {
    name: "Bunny's Bread Crumbs",
    image: "bunny-bread-crumps.webp",
    quantity: "200gm",
    discountPercentage: "",
    price: "120",
    category: "Bakery and Dairy",
    subcategory: "Breads",
    featured: false,
    topSeller: false,
  },
  {
    name: "Omega 3 Eggs Farm Fresh",
    image: "omega-eggs.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "374",
    category: "Bakery and Dairy",
    subcategory: "Eggs",
    featured: false,
    topSeller: false,
  },
  {
    name: "Classic Eggs Farm Fresh",
    image: "classic-eggs.webp",
    quantity: "12 piece",
    discountPercentage: "",
    price: "298",
    category: "Bakery and Dairy",
    subcategory: "Eggs",
    featured: false,
    topSeller: false,
  },
  {
    name: "Golden Eggs Farm Fresh",
    image: "golden-eggs.webp",
    quantity: "12 piece",
    discountPercentage: "",
    price: "339",
    category: "Bakery and Dairy",
    subcategory: "Eggs",
    featured: false,
    topSeller: false,
  },
  {
    name: "Kashmir Banaspati Ghee 1KG",
    image: "kashmir-banaspati-ghee.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "610",
    category: "Grocery",
    subcategory: "Oil and Ghee",
    featured: false,
    topSeller: false,
  },
  {
    name: "Canolive Cooking Oil 1 Litre Pouch",
    image: "canolive-cooking-oil.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "730",
    category: "Grocery",
    subcategory: "Oil and Ghee",
    featured: false,
    topSeller: false,
  },
  {
    name: "Kausar Canola Oil 1 Litre Pouch",
    image: "kausar-oil.webp",
    quantity: "1 ltr",
    discountPercentage: "",
    price: "620",
    category: "Grocery",
    subcategory: "Oil and Ghee",
    featured: false,
    topSeller: false,
  },
  {
    name: "Mitchells Vinegar",
    image: "mitchells-vinegar.webp",
    quantity: "310 ml",
    discountPercentage: "15",
    price: "100",
    category: "Grocery",
    subcategory: "Spices, Salt & Sugar",
    featured: false,
    topSeller: false,
  },
  {
    name: "Sugar 1Kg ATF",
    image: "sugar-atf.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "129",
    category: "Grocery",
    subcategory: "Spices, Salt & Sugar",
    featured: false,
    topSeller: false,
  },
  {
    name: "Shakarganj White Crystalline Sugar",
    image: "shakarganj-sugar.webp",
    quantity: "1 kg",
    discountPercentage: "",
    price: "130",
    category: "Grocery",
    subcategory: "Spices, Salt & Sugar",
    featured: false,
    topSeller: false,
  },
  {
    name: "Ginger (Adrak) Powder - ادرک پاوڈر",
    image: "adrak.webp",
    quantity: "100 gm",
    discountPercentage: "",
    price: "80",
    category: "Grocery",
    subcategory: "Spices, Salt & Sugar",
    featured: false,
    topSeller: false,
  },
  {
    name: "Guard Awami Basmati Rice 5KG",
    image: "guard-rice.webp",
    quantity: "5 kg",
    discountPercentage: "5",
    price: "1475",
    category: "Grocery",
    subcategory: "Daalein, Rice & Flour",
    featured: false,
    topSeller: false,
  },
  {
    name: "Punjab Atta 15KG",
    image: "punjab-atta.webp",
    quantity: "15 kg",
    discountPercentage: "",
    price: "2550",
    category: "Grocery",
    subcategory: "Daalein, Rice & Flour",
    featured: false,
    topSeller: false,
  },
  {
    name: "Anaaj Yousaf Chakki Atta (Whole Wheat Flour) 10kg",
    image: "yousaf-atta.jpeg",
    quantity: "10 kg",
    discountPercentage: "",
    price: "1700",
    category: "Grocery",
    subcategory: "Daalein, Rice & Flour",
    featured: false,
    topSeller: false,
  },
  {
    name: "National Apple Jam",
    image: "national-apple-jam.webp",
    quantity: "200 gm",
    discountPercentage: "",
    price: "175",
    category: "Grocery",
    subcategory: "Jam, Honey and Spread",
    featured: false,
    topSeller: false,
  },
  {
    name: "National Mix Fruit Jam Chunky with Fruit Chunks",
    image: "national-fruit-jam.webp",
    quantity: "385 gm",
    discountPercentage: "",
    price: "495",
    category: "Grocery",
    subcategory: "Jam, Honey and Spread",
    featured: false,
    topSeller: false,
  },
  {
    name: "Chicken Karahi Cut (چکن کراہی کٹ)",
    image: "chicken-karahi-cut.webp",
    quantity: "1000 gm",
    discountPercentage: "5",
    price: "629",
    category: "Meat",
    subcategory: "Chicken",
    featured: false,
    topSeller: false,
  },
  {
    name: "Chicken Biryani Cut - چکن بریانی کٹ",
    image: "chicken-biryani-cut.webp",
    quantity: "1000 gm",
    discountPercentage: "5",
    price: "629",
    category: "Meat",
    subcategory: "Chicken",
    featured: false,
    topSeller: false,
  },
  {
    name: "Chicken Thigh Bone In ( 4 PCS )",
    image: "chicken-thigh-bone.webp",
    quantity: "1 unit",
    discountPercentage: "5",
    price: "529",
    category: "Meat",
    subcategory: "Chicken",
    featured: false,
    topSeller: false,
  },
  {
    name: "Mutton Mix (مٹن مکس)",
    image: "mutton-mix.webp",
    quantity: "900 gm",
    discountPercentage: "",
    price: "1949",
    category: "Meat",
    subcategory: "Mutton",
    featured: false,
    topSeller: false,
  },
  {
    name: "Mutton Shoulder (مٹن دستی)",
    image: "mutton-shoulder.webp",
    quantity: "900 gm",
    discountPercentage: "",
    price: "2099",
    category: "Meat",
    subcategory: "Mutton",
    featured: false,
    topSeller: false,
  },
  {
    name: "Mutton Leg (مٹن ران)",
    image: "mutton-leg.webp",
    quantity: " 900 gm",
    discountPercentage: "",
    price: "2049",
    category: "Meat",
    subcategory: "Mutton",
    featured: false,
    topSeller: false,
  },
  {
    name: "Knorr Blazin Flavoured Instant Noodles",
    image: "knorr-blazing-noodles.webp",
    quantity: "124 gm",
    discountPercentage: "",
    price: "155",
    category: "Instant Food",
    subcategory: "Noodles",
    featured: false,
    topSeller: false,
  },
  {
    name: "Knorr Chatt Patta Instant Noodles",
    image: "knorr-chat-patta.webp",
    quantity: "61 gm",
    discountPercentage: "",
    price: "75",
    category: "Instant Food",
    subcategory: "Noodles",
    featured: false,
    topSeller: false,
  },
  {
    name: "Shan Shoop Cheese Flavour Instant Noodles",
    image: "shoop-cheese-noodles.webp",
    quantity: "82gm",
    discountPercentage: "",
    price: "70",
    category: "Instant Food",
    subcategory: "Noodles",
    featured: false,
    topSeller: false,
  },
  {
    name: "Knorr Chicken Instant Noodles",
    image: "knorr-chicken.webp",
    quantity: "61 gm",
    discountPercentage: "",
    price: "70",
    category: "Instant Food",
    subcategory: "Noodles",
    featured: false,
    topSeller: false,
  },
  {
    name: "Lu Tuc BP (1X16)",
    image: "tuc.webp",
    quantity: "1 unit",
    discountPercentage: "4",
    price: "231",
    category: "Instant Food",
    subcategory: "Biscuits & Cookies",
    featured: false,
    topSeller: false,
  },
  {
    name: "Bakeri Nankhatai BP (1X16)",
    image: "nankhatai.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "240",
    category: "Instant Food",
    subcategory: "Biscuits & Cookies",
    featured: false,
    topSeller: false,
  },
  {
    name: "Lu Bakeri Bistiks Family Pack",
    image: "bistiks.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "80",
    category: "Instant Food",
    subcategory: "Biscuits & Cookies",
    featured: false,
    topSeller: false,
  },
  {
    name: "CHEETOS CRUN RFH RS 30",
    image: "cheetos.webp",
    quantity: " 23 gm",
    discountPercentage: "",
    price: "30",
    category: "Instant Food",
    subcategory: "Chips & Nimko",
    featured: false,
    topSeller: false,
  },
  {
    name: "Kolson Jalapeno Slanty Rs 10",
    image: "slanty.webp",
    quantity: "5 gm",
    discountPercentage: "",
    price: "10",
    category: "Instant Food",
    subcategory: "Chips & Nimko",
    featured: false,
    topSeller: false,
  },
  {
    name: "Kolson Potato Sticks Rs 10",
    image: "potato-sticks.webp",
    quantity: "5 gm",
    discountPercentage: "",
    price: "10",
    category: "Instant Food",
    subcategory: "Chips & Nimko",
    featured: false,
    topSeller: false,
  },
  {
    name: "Kolson Salted Slanty Rs 10",
    image: "slanty-salted.webp",
    quantity: "5 gm",
    discountPercentage: "",
    price: "10",
    category: "Instant Food",
    subcategory: "Chips & Nimko",
    featured: false,
    topSeller: false,
  },
  {
    name: "Bounty Chocolate",
    image: "bounty.webp",
    quantity: "57 gm",
    discountPercentage: "",
    price: "189",
    category: "Instant Food",
    subcategory: "Chocolates",
    featured: false,
    topSeller: false,
  },
  {
    name: "M&M&s Peanut Chocolate Candy",
    image: "MandM.webp",
    quantity: "45 gm",
    discountPercentage: "",
    price: "159",
    category: "Instant Food",
    subcategory: "Chocolates",
    featured: false,
    topSeller: false,
  },
  {
    name: "Mars Chocolate Bar",
    image: "mars.webp",
    quantity: "51 gm",
    discountPercentage: "",
    price: "165",
    category: "Instant Food",
    subcategory: "Chocolates",
    featured: false,
    topSeller: false,
  },
  {
    name: "7Up Drink",
    image: "7up.webp",
    quantity: "1.5 Litre",
    discountPercentage: "17",
    price: "160",
    category: "Beverages",
    subcategory: "Cold Drinks",
    featured: false,
    topSeller: false,
  },
  {
    name: "Sprite Drink",
    image: "sprite.webp",
    quantity: "1 Litre",
    discountPercentage: "10",
    price: "120",
    category: "Beverages",
    subcategory: "Cold Drinks",
    featured: false,
    topSeller: false,
  },
  {
    name: "Coca Cola Soft Drink",
    image: "coca-cola.webp",
    quantity: "1.5 ltr",
    discountPercentage: "12",
    price: "140",
    category: "Beverages",
    subcategory: "Cold Drinks",
    featured: false,
    topSeller: false,
  },
  {
    name: "Nestle Fruita Vitals Apple 1 Litre",
    image: "nestle-apple.webp",
    quantity: "1 ltr",
    discountPercentage: "5",
    price: "299",
    category: "Beverages",
    subcategory: "Juices",
    featured: false,
    topSeller: false,
  },
  {
    name: "Fruitien Juice Chaunsa Mango Nectar Juice",
    image: "fruitien.webp",
    quantity: "200 ml",
    discountPercentage: "10",
    price: "60",
    category: "Beverages",
    subcategory: "Juices",
    featured: false,
    topSeller: false,
  },
  {
    name: "Slice Mango Fruit Drink",
    image: "slice-mango.webp",
    quantity: "200 ml",
    discountPercentage: "",
    price: "35",
    category: "Beverages",
    subcategory: "Juices",
    featured: false,
    topSeller: false,
  },
  {
    name: "Tapal Danedar Black Tea",
    image: "tapal.webp",
    quantity: "430 gm",
    discountPercentage: "6",
    price: "820",
    category: "Beverages",
    subcategory: "Tea",
    featured: false,
    topSeller: false,
  },
  {
    name: "Tapal Family Mixture Economy Pack Tea",
    image: "tapal-economy.webp",
    quantity: "900 gm",
    discountPercentage: "7",
    price: "1700",
    category: "Beverages",
    subcategory: "Tea",
    featured: false,
    topSeller: false,
  },
  {
    name: "Vital Black Tea Pouch",
    image: "vital.webp",
    quantity: "900 gm",
    discountPercentage: "9",
    price: "1714",
    category: "Beverages",
    subcategory: "Tea",
    featured: false,
    topSeller: false,
  },
  {
    name: "Harpic Bathroom Cleaner Floral",
    image: "harpic.webp",
    quantity: "500 ml",
    discountPercentage: "",
    price: "449",
    category: "Home Care",
    subcategory: "Floor, Bath Cleaning",
    featured: false,
    topSeller: false,
  },
  {
    name: "Harpic Power Plus 10X clean citrus",
    image: "harpic-power.webp",
    quantity: " 1000 ml",
    discountPercentage: "",
    price: "645",
    category: "Home Care",
    subcategory: "Floor, Bath Cleaning",
    featured: false,
    topSeller: false,
  },
  {
    name: "Dettol Multi Purpose Cleaner Aqua",
    image: "dettol.webp",
    quantity: "500 ml",
    discountPercentage: "",
    price: "485",
    category: "Home Care",
    subcategory: "Floor, Bath Cleaning",
    featured: false,
    topSeller: false,
  },
  {
    name: "Sunlight 2 in 1 clean & jasmine fresh",
    image: "sunlight.webp",
    quantity: "850 gm",
    discountPercentage: "",
    price: "199",
    category: "Home Care",
    subcategory: "Laundry",
    featured: false,
    topSeller: false,
  },
  {
    name: "Sunlight 2 in 1 clean & rose fresh",
    image: "sunlight-rose-clean.webp",
    quantity: "850 gm",
    discountPercentage: "",
    price: "199",
    category: "Home Care",
    subcategory: "Laundry",
    featured: false,
    topSeller: false,
  },
  {
    name: "Lemon Max Anti-Bacterial Dishwash Liquid Bottle 475ml",
    image: "lemon-dishwash.webp",
    quantity: "475 ml",
    discountPercentage: "",
    price: "270",
    category: "Home Care",
    subcategory: "Kitchen, Glass & Drain Cleaners",
    featured: false,
    topSeller: false,
  },
  {
    name: "Lemon Max Anti-Bacterial Dishwash Powder Bag 790g",
    image: "lemon-powder.webp",
    quantity: "790 gm",
    discountPercentage: "",
    price: "140",
    category: "Home Care",
    subcategory: "Kitchen, Glass & Drain Cleaners",
    featured: false,
    topSeller: false,
  },
  {
    name: "Lemon Max Dishwash Liquid Bottle 750ml",
    image: "lemon-liquid.webp",
    quantity: "750 ml",
    discountPercentage: "",
    price: "350",
    category: "Home Care",
    subcategory: "Kitchen, Glass & Drain Cleaners",
    featured: false,
    topSeller: false,
  },
  {
    name: "Gillete Blue 3 Pack Of 3",
    image: "gillete.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "799",
    category: "Personal Care",
    subcategory: "Men Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Nike Man Green Deodorant",
    image: "Nike.webp",
    quantity: "200 ml",
    discountPercentage: "",
    price: "495",
    category: "Personal Care",
    subcategory: "Men Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Black Collection Pulse",
    image: "bold.webp",
    quantity: "120 ml",
    discountPercentage: "",
    price: "410",
    category: "Personal Care",
    subcategory: "Men Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Sunsilk Hairfall Solution Shampoo",
    image: "sunsilk.webp",
    quantity: "185 ml",
    discountPercentage: "",
    price: "349",
    category: "Personal Care",
    subcategory: "Hair Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Palmolive Intensive Moisture Shampoo",
    image: "palmolive.webp",
    quantity: "180 ml",
    discountPercentage: "",
    price: "299",
    category: "Personal Care",
    subcategory: "Hair Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Lifebuoy Naturally Long Shampoo",
    image: "lifebouy.webp",
    quantity: "370 ml",
    discountPercentage: "",
    price: "510",
    category: "Personal Care",
    subcategory: "Hair Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Fair & Lovely Fairness Cream Advance Multi Vitamin",
    image: "fair & lovely.webp",
    quantity: "50 gm",
    discountPercentage: "",
    price: "220",
    category: "Personal Care",
    subcategory: "Skin Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Ponds Pure Bright Facewash",
    image: "ponds.webp",
    quantity: "100 gm",
    discountPercentage: "",
    price: "380",
    category: "Personal Care",
    subcategory: "Skin Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Ponds Pimple Clear Face Wash",
    image: "ponds-face-wash.webp",
    quantity: "100 gm",
    discountPercentage: "",
    price: "380",
    category: "Personal Care",
    subcategory: "Skin Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Nestle Nido 1+",
    image: "nestle-nido.webp",
    quantity: " 375 gm",
    discountPercentage: "",
    price: "860",
    category: "Baby Care",
    subcategory: "Food & Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Nestle Bunyad",
    image: "nestle-bunyad.webp",
    quantity: "900 gm",
    discountPercentage: "",
    price: "1350",
    category: "Baby Care",
    subcategory: "Food & Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Nestle Cerelac 3 Fruit & Wheat",
    image: "cerelac.webp",
    quantity: "175 gm",
    discountPercentage: "",
    price: "335",
    category: "Baby Care",
    subcategory: "Food & Milk",
    featured: false,
    topSeller: false,
  },
  {
    name: "Canbebe Primary Care Baby Wipes",
    image: "canbaby-wipes.webp",
    quantity: "56 piece",
    discountPercentage: "",
    price: "355",
    category: "Baby Care",
    subcategory: "Diaper & Wipes",
    featured: false,
    topSeller: false,
  },
  {
    name: "Canbebe Diapers Size 5 (11-25kg)",
    image: "canbebe-diapers.webp",
    quantity: "28 piece",
    discountPercentage: "",
    price: "1750",
    category: "Baby Care",
    subcategory: "Diaper & Wipes",
    featured: false,
    topSeller: false,
  },
  {
    name: "Pampers Skin Comfort Pants (14-19kg)",
    image: "pamper.webp",
    quantity: "38 piece",
    discountPercentage: "",
    price: "2299",
    category: "Baby Care",
    subcategory: "Diaper & Wipes",
    featured: false,
    topSeller: false,
  },
  {
    name: "Johnsons Baby Milk Soap",
    image: "johnsons.webp",
    quantity: " 100 gm",
    discountPercentage: "",
    price: "228",
    category: "Baby Care",
    subcategory: "Bath & Skin Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Colgate Extra Soft Kids Tooth Brush",
    image: "colgate.webp",
    quantity: "1 unit",
    discountPercentage: "",
    price: "70",
    category: "Baby Care",
    subcategory: "Bath & Skin Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Aveeno Baby Carrier Cream",
    image: "aveeno-baby.webp",
    quantity: "100 ml",
    discountPercentage: "",
    price: "2264",
    category: "Baby Care",
    subcategory: "Bath & Skin Care",
    featured: false,
    topSeller: false,
  },
  {
    name: "Akhrot 100GM (اخروٹ)",
    image: "akhrot.webp",
    quantity: "100 gm",
    discountPercentage: "5",
    price: "314",
    category: "Dry Fruits and Nuts",
    subcategory: "Nuts",
    featured: false,
    topSeller: false,
  },
  {
    name: "Pistachio Roasted 100 GM (پستہ بھنا ہوا)",
    image: "pista.webp",
    quantity: "100 gm",
    discountPercentage: "5",
    price: "419",
    category: "Dry Fruits and Nuts",
    subcategory: "Nuts",
    featured: false,
    topSeller: false,
  },
  {
    name: "Kaju Roasted 100 GM (کاجو بھنے ہوئے)",
    image: "kaju.webp",
    quantity: "100 gm",
    discountPercentage: "10",
    price: "398",
    category: "Dry Fruits and Nuts",
    subcategory: "Nuts",
    featured: false,
    topSeller: false,
  },
  {
    name: "Khoobani Gol. 200GM (خوبانی گول)",
    image: "khoobani.webp",
    quantity: "200 gm",
    discountPercentage: "10",
    price: "332",
    category: "Dry Fruits and Nuts",
    subcategory: "Dry Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Khoobani Crystal 200GM (خوبانی کرسٹل)",
    image: "khoobani-crystal.webp",
    quantity: "200 gm",
    discountPercentage: "10",
    price: "376",
    category: "Dry Fruits and Nuts",
    subcategory: "Dry Fruits",
    featured: false,
    topSeller: false,
  },
  {
    name: "Dawn Chicken Kofta 8 Pieces (267g)",
    image: "dawn-kofta.jpeg",
    quantity: "267 gm",
    discountPercentage: "",
    price: "425",
    category: "Frozen and Chilled",
    subcategory: "Kabab & Kofta",
    featured: false,
    topSeller: false,
  },
  {
    name: "K&N's Shami Kabab 18 Pieces (648g)",
    image: "KandN's-shami.webp",
    quantity: " 648 gm",
    discountPercentage: "",
    price: "1025",
    category: "Frozen and Chilled",
    subcategory: "Kabab & Kofta",
    featured: false,
    topSeller: false,
  },
  {
    name: "K&N's Jumbo Frank Sausage Cheese and Onion 10 Pieces",
    image: "k&n-sausage.webp",
    quantity: "740 gm",
    discountPercentage: "",
    price: "1120",
    category: "Frozen and Chilled",
    subcategory: "Sausages & Toppings",
    featured: false,
    topSeller: false,
  },
  {
    name: "K&N's Toppingz 'N Fillingz Fajita 650g",
    image: "k&n-toppin.webp",
    quantity: "650 gm",
    discountPercentage: "",
    price: "1250",
    category: "Frozen and Chilled",
    subcategory: "Sausages & Toppings",
    featured: false,
    topSeller: false,
  },
];
